# 1. Use an official Node environment
FROM node:18-alpine

# 2. Set the working directory
WORKDIR /app

# 3. Copy package.json and install dependencies
COPY package*.json ./

# 4. Install dependencies using npm ci
RUN npm ci

# 4. Copy the rest of your frontend code
COPY . .

# 5. Expose the port your frontend runs on (let's assume 3000 for React)
EXPOSE 5173

# 6. The command to start your frontend (might be 'npm run dev' depending on your setup)
CMD ["npm", "run", "dev","--", "--host"]